### ISSUE TITLE
Question about Iterative Modified Gram-Schimidt

### ISSUE THREAD

**Issue by zbzhu99** [HeegerGao/RiEMann#1]
Thank you for open-sourcing this wonderful repo! 

I am currently trying the evaluation script, and I've noticed something I'd like to understand better. When evaluating new poses, the predicted axes are processed by Iterative Modified Gram-Schimidtt to get a legal rotation matrix:

https://github.com/HeegerGao/RiEMann/blob/95a3dfa6c3bd80945032118fa7c344fbe232aa44/scripts/testing/infer.py#L59

I noticed that you transposed the matrix before input to `modified_gram_schmidt()` but the output is not transposed back. Could you provide some insight into the reasoning behind not transposing the output?

**Comment by HeegerGao** [comment]
Hello Zhengbang,

Thanks for your interest in RiEMann. 

The variable `output_direction` in line 59 is in the shape of [1, 9], which can also be seen as [$`v_1^T`$, $`v_2^T`$, $`v_3^T`$], where a legal rotation matrix is $`R=[v_1, v_2, v_3]`$. Thus, in line 59, we first reshape it from [1, 9] to the shape [3, 3], then we transpose it to get a legal rotation matrix, and finally, we send it through the `modified_gram_schmidt` function.

The output of `modified_gram_schmidt` is already a legal rotation matrix, so we do not need to transpose it again.

**Comment by HeegerGao** [comment]
I will close this issue. Feel free to reopen it if you still have any question.

**Comment by zbzhu99** [comment]
Thank you for your reply!
